db-uri = "postgres://indusia_user:LZU8nLlSeWsCj24Z@localhost:5432/indusia_db"
db-schemas = "public"
db-anon-role = "indusia_user"
server-port = 3001

# JWT Configuration for local development
jwt-secret = "c102d75e7de1a92f0913ba0c195693df1e047c7468bf2a7e42aaa56c5f54b124"
jwt-aud = "local"
